name: gargantua-test

services:
    postgres:
        image: postgres:17.0-alpine
        restart: no
        ports:
            - "127.0.0.1:5432:5432"
        #TODO: change user and password before deploy
        environment:
            POSTGRES_USER: superuser
            POSTGRES_PASSWORD: superpassword
            POSTGRES_DB: gargantua_db
        volumes:
        - gargantua-test-postgres:/var/lib/postgresql/gargantua_db

    #TODO: should I keep pgadmin?
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: no
        ports:
            - "127.0.0.1:8080:80"
        environment:
            #TODO: change user and password before deploy
            PGADMIN_DEFAULT_EMAIL: a@a.com
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        volumes:
        - gargantua-test-pgadmin:/var/lib/pgadmin
        depends_on:
        - postgres

    redis:
        image: redis:latest
        command:
        - redis-server
        environment:
            - REDIS_DATABASE=1
            - REDIS_HOST=localhost
            - REDIS_PORT=6379
            - REDIS_USERNAME=default
            - REDIS_PASSWORD=default
            - REDIS_TTL_STATE=None
            - REDIS_TTL_DATA=None
        restart: no
        ports:
        - "127.0.0.1:6379:6379"
        

volumes:
    gargantua-test-pgadmin:
    gargantua-test-postgres:
